### ISSUE TITLE
Select cu ripigliammo? Usa piglie o piglia

### ISSUE THREAD

**Issue by rosarioconti** [aurasphere/gomorra-sql#12]
Select cu ripigliammo? Usa piglie o piglia

**Comment by aurasphere** [comment]
Ciao Rosario e grazie per la segnalazione! Il senso della scelta è stato quello di ricalcare una delle frasi più famose di Gomorra che appunto è “Mo ce ripigliamm’ tutt’ chell che è ’o nuost’”. Sostituire ripigliammo con piglie o piglia sarebbe sicuramente più corretto in napoletano, ma purtroppo il progetto si chiama GomorraSQL, non NapoliSQL!
