### ISSUE TITLE
Stima

### ISSUE THREAD

**Issue by Lojacops** [aurasphere/gomorra-sql#3]
Ok che è un issue, ma volevo complimentarvi con voi, mio signore.

**Comment by aurasphere** [comment]
Grazie, per i complimenti. Se vuoi ti nomino mio vassallo :P

**Comment by Lojacops** [comment]
> Grazie, per i complimenti. Se vuoi ti nomino mio vassallo :P

Ne sarei felice anche se non sviluppo in java
